# Generated by Django 2.2.7 on 2019-11-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LISTA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
